### ISSUE TITLE
Another implementaion for Node.js with better performance and Support Matrix

### ISSUE THREAD

**Issue by Brooooooklyn** [connor4312/blake3#36]
Here is the repo: https://github.com/Brooooooklyn/blake-hash

**Comment by oconnor663** [comment]
My understanding is that both libraries are bindings for the same Rust library. Is it possible that the benchmark wasn't testing them in the same configuration? Or is there a real performance difference to do with e.g. performing fewer memory copies?

**Comment by connor4312** [comment]
Nice work. By the way the reason you see a large speed difference in your version is the latest version of blake3 lacks Node 16 native Neon bindings, so you're actually testing the wasm version which is indeed much slower.

Initially there was build issues with npm in Node 15 that included the ABI version 16 uses. It seems that's now resolve, and although wasm-pack recently broke (https://github.com/rustwasm/wasm-pack/issues/1079) tha can be fixed with a downgrade.

Anyway, with a bumped up version of blake3 (both this module and the source crate) performance is quite comparable:

```
Running "digest big file blake3" suite...
Progress: 100%

  blake3-napi:
    6 740 ops/s, ±1.30%   | fastest

  blake3-neon:
    6 655 ops/s, ±1.54%   | slowest, 1.26% slower

Finished 2 cases!
  Fastest: blake3-napi
  Slowest: blake3-neon
```

**Comment by Brooooooklyn** [comment]
I'll update the benchmark result, thanks for your explanation.

**Comment by CumpsD** [comment]
@connor4312 trying to understand your reply.

Which version exactly has the native bindings?
